### ISSUE TITLE
Getting Error pixReadFromTiffStream

### ISSUE THREAD

**Issue by balli1187** [PhilippMundhenk/TesseractOCRMicroservice#1]
Hi,

i've been using your brother container for a while and now wanted to add OCR with this container.

containers are running and seem to interact but unfortunately i get this errer
`Error in pixReadFromTiffStream: spp not in set {1,3,4}` and the *-ocr.pdf is just a few (k)bytes.

any idea how to fix it?

Regards, Stephan

**Comment by PhilippMundhenk** [comment]
Hi @balli1187,
based on https://stackoverflow.com/questions/5083492/tesseract-and-tiff-format-spp-not-in-set-1-3, it seems there are some alpha channels in the converted tiff image. Not sure why, but I try to get rid of them in the conversion step with the commit I just pushed. Have a try.

**Comment by PhilippMundhenk** [comment]
closed for inactivity
